name: Check Links

on:
  schedule:
    - cron: '37 8 * * 1'  # weekly on Monday
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-path 'modules/paper-corpus' --exclude 'localhost' '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
